### ISSUE TITLE
Cannot access actor's sheet after apply Mighty Morphin Beast Wild 

### ISSUE THREAD

**Issue by guillaume-gc** [websterguy/pf1-mighty-morphin-mod#20]
Just after applying Beast Wild IV, I cannot open the affected actor's sheet.

The following error is thrown every time I try to open the sheet:
```
TypeError: Cannot read properties of undefined (reading 'forEach')
[Detected 1 package: system:pf1]
    at Array.<anonymous> (helpers.js:119:12)
    at Array.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:155)
    at Object.h [as fn] (handlebars.min.js:27:17870)
    at Array.<anonymous> (handlebars.min.js:27:10117)
    at Array.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:12:47)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at ItemAction.<anonymous> (handlebars.min.js:27:7289)
    at ItemAction.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:10:52)
    at h (handlebars.min.js:27:17870)
    at ItemData.<anonymous> (handlebars.min.js:27:11317)
    at ItemData.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:17:49)
    at Object.h [as fn] (handlebars.min.js:27:17870)
    at ItemData.<anonymous> (handlebars.min.js:27:10117)
    at ItemData.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:21:47)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at Object.<anonymous> (handlebars.min.js:27:7289)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:31:49)
    at Object.h [as inverse] (handlebars.min.js:27:17870)
    at Object.<anonymous> (handlebars.min.js:27:10101)
    at Object.<anonymous> (handlebars.min.js:27:10278)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:10:54)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at handlebars.min.js:27:7554
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7522
    at Object.<anonymous> (handlebars.min.js:27:7597)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:83:49)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:41:28)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:4696:10)
    at async ActorSheetPFCharacter._renderInner (foundry.js:3235:16)
    at async ActorSheetPFCharacter._renderInner (foundry.js:3775:18)
    at async ActorSheetPFCharacter._render (foundry.js:3068:19)
    at async ActorSheetPFCharacter._render (foundry.js:3764:5)
    at async ActorSheetPFCharacter._render (base.js:2812:11)
```

Their sheet is accessible before and after applying Mighty Beast.

**Comment by websterguy** [comment]
Are you on the latest version? This should have been fixed less than a day ago.

**Comment by guillaume-gc** [comment]
Well, it's getting a bit awkward...

I wasn't on the latest version, so I updated to 0.3.13. In this version, it seems the `game.mightyMorphin` object doesn't exist anymore. Everytime I tried to call it it triggers this error: `TypeError: Cannot read properties of undefined (reading 'xxx')`.

For example if I call `game.mightyMorphin.revert()`, it triggers this error: `TypeError: Cannot read properties of undefined (reading 'revert')`.

I console logged `game`, and `mightyMorphin` is nowhere to be seen.

I tried uninstalling and reinstalling the module, it didn't solve this issue.

So I downgraded to 0.3.12.2 and now everything seems to be working perfectly.

Do you want me to close this issue and open another one, perhaps?

**Comment by websterguy** [comment]
Update again
